<a href="https://colab.research.google.com/github/sprawesh/IME692Fall2022/blob/main/FactorAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#install factor analyzer
!pip install factor_analyzer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 41 kB 436 kB/s 
  Created wheel for factor-analyzer: filename=factor_analyzer-0.4.0-py3-none-any.whl size=41455 sha256=d51db99735fc2955592d5612ea25756ea871578d6ea5e82ac01c9fe14405908a
  Stored in directory: /root/.cache/pip/wheels/ac/00/37/1f0e8a5039f9e9f207c4405bbce0796f07701eb377bfc6cc76
Successfully built factor-analyzer


In [3]:
import pandas as pd
from factor_analyzer import FactorAnalyzer

In [4]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount = True)

Mounted at /content/gdrive


In [8]:
path = '/content/gdrive/MyDrive/Colab Notebooks/test02.csv'
data = pd.read_csv(path)

In [9]:
fa = FactorAnalyzer(rotation='varimax')
fa.fit(data)

FactorAnalyzer(rotation='varimax', rotation_kwargs={})

In [11]:
import numpy as np
np.set_printoptions(precision=3)
print(fa.loadings_)

[[-0.077  0.045  0.762]
 [ 0.018  0.058  0.013]
 [ 0.061  0.707 -0.033]
 [ 0.113  0.845 -0.034]
 [ 0.153  0.555 -0.001]
 [ 0.775  0.147  0.201]
 [ 0.706  0.172 -0.301]
 [ 0.84   0.151 -0.062]
 [ 0.766  0.105 -0.226]
 [ 0.814  0.209  0.075]]


In [12]:
#the 1st factor has high loadings on: english, math, soc_sci, natural sc., and vocabulary
#the 2nd factor has high loadings on: mo_ed, fa_ed, fami_nc
print(fa.get_communalities())

[0.589 0.004 0.505 0.728 0.332 0.662 0.619 0.732 0.649 0.711]
