<a href="https://colab.research.google.com/github/sprawesh/IME692Fall2022/blob/main/IME692cov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount = True)

Mounted at /content/gdrive


In [ ]:
import numpy as np
from sklearn.covariance import EmpiricalCovariance

In [ ]:
# read a file and convert it into array with shape (n_sample, n_features)
# dataset is available at https://github.com/QuantLet/MVA/tree/master/QID-945-MVApcabank
path = '/content/gdrive/MyDrive/Colab Notebooks/bank2.txt'
data = np.loadtxt(path)
print(data.shape)

(200, 6)


In [ ]:
data[:5,] # first five rows

array([[214.8, 131. , 131.1,   9. ,   9.7, 141. ],
       [214.6, 129.7, 129.7,   8.1,   9.5, 141.7],
       [214.8, 129.7, 129.7,   8.7,   9.6, 142.2],
       [214.8, 129.7, 129.6,   7.5,  10.4, 142. ],
       [215. , 129.6, 129.7,  10.4,   7.7, 141.8]])

In [ ]:
#copy first 100 rows -genuine, remaining -counterfeit
fake = np.copy(data) # because modified and original array share memory block
fake1 = fake[100:,]

In [ ]:
print(fake1.shape)

(100, 6)


In [ ]:
fake1[:5,]

array([[214.4, 130.1, 130.3,   9.7,  11.7, 139.8],
       [214.9, 130.5, 130.2,  11. ,  11.5, 139.5],
       [214.9, 130.3, 130.1,   8.7,  11.7, 140.2],
       [215. , 130.4, 130.6,   9.9,  10.9, 140.3],
       [214.7, 130.2, 130.3,  11.8,  10.9, 139.7]])

In [ ]:
genuine = data[:100,]
print(genuine.shape)

(100, 6)


In [ ]:
genuine[95:,]

array([[215.6, 129.9, 129.9,   9. ,   9.5, 141.7],
       [215. , 130.4, 130.3,   9.1,  10.2, 141.1],
       [214.4, 129.7, 129.5,   8. ,  10.3, 141.2],
       [215.1, 130. , 129.8,   9.1,  10.2, 141.5],
       [214.7, 130. , 129.4,   7.8,  10. , 141.2]])

In [ ]:
covf = EmpiricalCovariance().fit(fake1)
covg = EmpiricalCovariance().fit(genuine)

In [ ]:
covf1 = np.round(covf.covariance_, decimals=3)
covf1

array([[ 0.123,  0.031,  0.024, -0.1  ,  0.019,  0.011],
       [ 0.031,  0.064,  0.046, -0.024, -0.012, -0.005],
       [ 0.024,  0.046,  0.088, -0.018,  0.   ,  0.034],
       [-0.1  , -0.024, -0.018,  1.269, -0.485,  0.236],
       [ 0.019, -0.012,  0.   , -0.485,  0.4  , -0.022],
       [ 0.011, -0.005,  0.034,  0.236, -0.022,  0.308]])

In [ ]:
covg1 = np.round(covg.covariance_, decimals=3)
covg1

array([[ 0.149,  0.057,  0.057,  0.057,  0.014,  0.005],
       [ 0.057,  0.131,  0.085,  0.056,  0.049, -0.043],
       [ 0.057,  0.085,  0.125,  0.058,  0.03 , -0.024],
       [ 0.057,  0.056,  0.058,  0.409, -0.261, -0.   ],
       [ 0.014,  0.049,  0.03 , -0.261,  0.417, -0.075],
       [ 0.005, -0.043, -0.024, -0.   , -0.075,  0.198]])

In [ ]:
import pandas as pd
pd.DataFrame(covg1, columns=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'), 
             index=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'))

V1     v2     v3     v4     V5     V6
V1  0.149  0.057  0.057  0.057  0.014  0.005
v2  0.057  0.131  0.085  0.056  0.049 -0.043
v3  0.057  0.085  0.125  0.058  0.030 -0.024
v4  0.057  0.056  0.058  0.409 -0.261 -0.000
V5  0.014  0.049  0.030 -0.261  0.417 -0.075
V6  0.005 -0.043 -0.024 -0.000 -0.075  0.198

In [ ]:
pd.DataFrame(covf1, columns=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'), 
             index=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'))
#v4 has negative correlation with other variables

V1     v2     v3     v4     V5     V6
V1  0.123  0.031  0.024 -0.100  0.019  0.011
v2  0.031  0.064  0.046 -0.024 -0.012 -0.005
v3  0.024  0.046  0.088 -0.018  0.000  0.034
v4 -0.100 -0.024 -0.018  1.269 -0.485  0.236
V5  0.019 -0.012  0.000 -0.485  0.400 -0.022
V6  0.011 -0.005  0.034  0.236 -0.022  0.308

In [ ]:
#correlation matrix for fake
diagf = np.diag(covf1)
l1 = np.sqrt(diagf)
num = np.ones(6)
d1 = np.divide(num, l1)

In [ ]:
s = np.diag(d1)
R = np.matmul(s, covf1)
R1 = np.matmul(R, s)

In [ ]:
pdf2 = pd.DataFrame(np.round(R1, decimals=3), columns=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'),
            index=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'))

st = pdf2.to_string()
with open("/content/gdrive/MyDrive/Colab Notebooks/cov_f.txt", "w+") as file:
    file.write(st)

In [ ]:
#correlation matrix for genuine
diag2 = np.diag(covg1)
l2 = np.sqrt(diag2)
num = np.ones(6)
d2 = np.divide(num, l2)

s = np.diag(d2)
R = np.matmul(s, covg1)
R2 = np.matmul(R, s)

pdgf = pd.DataFrame(np.round(R2, decimals=3), columns=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'),
            index=('V1', 'v2', 'v3', 'v4', 'V5', 'V6'))


In [ ]:
#append result to the same file. 
st = pdgf.to_string()
with open("/content/gdrive/MyDrive/Colab Notebooks/cov_f.txt", "a") as file:
    file.write("\n")   
    file.write(st)
    
#V4, V5 show different relationships